#+title: CSS Font size
#+date: <2020-07-03 08:57>

* Reference
This page is copied from https://www.w3schools.com/css/css_font_size.asp, all rights reserved by the original owner.

* Font Size
The font-size property sets the size of the text.

Being able to manage the text size is important in web design. However, you should not use font size adjustments to make paragraphs look like headings, or headings look like paragraphs.

Always use the proper HTML tags, like <h1> - <h6> for headings and <p> for paragraphs.

The font-size value can be an absolute, or relative size.

Absolute size:

- Sets the text to a specified size
- Does not allow a user to change the text size in all browsers (bad for accessibility reasons)
- Absolute size is useful when the physical size of the output is known

Relative size:

- Sets the size relative to surrounding elements
- Allows a user to change the text size in browsers

* Set Font Size With Pixels
Setting the text size with pixels gives you full control over the text size:

#+BEGIN_SRC css
h1 {
  font-size: 40px;
}

h2 {
  font-size: 30px;
}

p {
  font-size: 14px;
}
#+END_SRC
